### ISSUE TITLE
Content is not being loaded on Iphone 4 - IOS 7.1.2

### ISSUE THREAD

**Issue by PedroVPP** [magalhini/firstaidgit#1]
I don't know it the problem lies with my phone, but the phrase "Loading content... help is on the way" keeps on showing forever and the content is never loaded. The problem happens both in Safari and Chrome.

![foto](https://cloud.githubusercontent.com/assets/209635/7229959/c5238494-e73f-11e4-8a74-664b81ce45f7.PNG)

**Comment by magalhini** [comment]
@PedroVPP True, I also noticed this the other day, I think the es6-promise plugin is failing as a fallback, so I'll probably take it out and switch to a regular XHR request. It was meant to be used as a test anyway, so it's not like it's absolutely necessary. I'll have a look at this soon :)

**Comment by magalhini** [comment]
Tested now on iOS 7 (iPad), seems to work nicely.
